### ISSUE TITLE
Access profiles and Network Access profiles in partitions

### ISSUE THREAD

**Issue by yzfvroom** [pwhitef5/apm-vpn-optimisation#1]
We have about 62 partitions with access profiles, network access profiles, network access lease pools and connectivity profiles for each of those partitions. Can this be modified to work with partitions?

**Comment by pwhitef5** [comment]
Thanks for the suggestions - I have updated the script to loop through all admin partitions and print out. Maybe you can test it out and let me know if it fits your needs
